version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9010:9000
    volumes:
      - hadoop_namenode:/docker-hadoop/dfs/name
      - ./share:/share
    working_dir: /share
    environment:
      - CLUSTER_NAME=cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.10

  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-1
    hostname: datanode-1
    restart: always
    volumes:
      - hadoop_datanode-1:/docker-hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.11

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2
    hostname: datanode-2
    restart: always
    volumes:
      - hadoop_datanode-2:/docker-hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.8

  datanode-3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-3
    hostname: datanode-3
    restart: always
    volumes:
      - hadoop_datanode-3:/docker-hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.9

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864"
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.12

  nodemanager:
    # image: bde2020/docker-hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    build:
      context: ./nodemanager
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088"
    ports:
      - "8042:8042"
    volumes:
      - hadoop_namenode:/docker-hadoop/dfs/name
      - ./share:/share
    working_dir: /share
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.13

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    hostname: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 datanode-3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/docker-hadoop/yarn/timeline
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env
    networks:
      net:
        ipv4_address: 172.20.20.14

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    depends_on:
      - namenode
      - datanode-1
      - datanode-2
      - datanode-3
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      net:
        ipv4_address: 172.20.20.15

  spark-worker:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      net:
        ipv4_address: 172.20.20.16

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/24

volumes:
  hadoop_namenode:
  hadoop_datanode-1:
  hadoop_datanode-2:
  hadoop_datanode-3:
  hadoop_historyserver:

